replicaCount: 1

image:
  nginx:
    repository: nginx
    tag: latest
  busybox:
    repository: busybox
    tag: 1.28.4

service:
  type: NodePort
  port: 80
  nodePort: 32000

nodeSelector: {}
tolerations: []
affinity: {}
resources: {}
