apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-git-sync
  labels:
    app: sidecar
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sidecar
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: sidecar
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: ctr-web
        image: {{ .Values.image.nginx.repository }}:{{ .Values.image.nginx.tag }}
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      - name: ctr-sync
        image: {{ .Values.image.gitSync.repository }}:{{ .Values.image.gitSync.tag }}
        volumeMounts:
        - name: html
          mountPath: /tmp/git
        env:
        - name: GIT_SYNC_REPO
          value: {{ .Values.gitSync.repo | quote }}
        - name: GIT_SYNC_BRANCH
          value: {{ .Values.gitSync.branch | quote }}
        - name: GIT_SYNC_DEPTH
          value: {{ .Values.gitSync.depth | quote }}
        - name: GIT_SYNC_DEST
          value: {{ .Values.gitSync.dest | quote }}
      volumes:
      - name: html
        emptyDir: {}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
