apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc-sidecar
  labels:
    app: sidecar
    release: {{ .Release.Name }}
spec:
  selector:
    app: sidecar
    release: {{ .Release.Name }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
  type: {{ .Values.service.type }}
