pod:
  name: hello-pod
  labels:
    zone: prod
    version: v1

container:
  name: hello-ctr
  image: nigelpoulton/k8sbook:1.0
  ports:
    containerPort: 8080
  resources:
    limits:
      memory: 256Mi
      cpu: 0.5

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30080
